import os

TILE_SIZE = 80
PLAYER_DISPLAY_SIZE = 140
PLAYER_INTERACTION_AREA_SIZE = 20
SPEED = 5 # = 5

# File pathes
BASE_PATH = os.path.dirname(os.path.abspath(__file__))
SPRITES_PATH = os.path.join(BASE_PATH, "sprites")

# Maps
MAPS_DATA = {

    (0, 0): [
[["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"]],
[["water","barrier"],["water"],["water"],["water"],["water"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water","tree_tr"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"]],
[["water","barrier"],["water"],["water"],["water","water_rock3"],["water"],["water","water_rock2"],["water"],["water_grass_br","tree_ml"],["grass_water_tc","tree_mc"],["water_grass_bl","tree_mr"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water","water_rock2"],["water"]],
[["water","barrier"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["grass_water_ml","tree_bl"],["grass","tree_bc"],["grass_water_mr","tree_br"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"]],
[["water","barrier"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"]],
[["water","barrier"],["water"],["water","water_rock2"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["grass_water_ml"]],
[["grass_water_tc","barrier"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tl"]],
[["grass","barrier"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tl"],["grass"],["grass","grass_rock5"]],
[["grass","barrier"],["grass_water_mr"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass_water_tl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock3"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass","grass_rock5"],["grass"],["grass"],["grass"],["grass","grass_big_rock_tl"],["grass","grass_big_rock_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]]
    ],

    (1, 0): [
[["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water_grass_tr","barrier"],["grass_water_bc","barrier"],["grass_water_bc","barrier"],["grass_water_bl","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier","tree_tl"],["grass","barrier","tree_tc"],["grass","barrier","tree_tr"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"]],
[["grass_water_tc","tree_tl"],["grass_water_tc","tree_tc"],["grass_water_tc","tree_tr"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock1"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"]],
[["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water","water_rock2"],["water"],["water","trunk_top"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","tree_tl"],["grass","tree_tc"],["grass_water_tr","tree_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water","trunk_bottom"],["water"],["water"],["water","water_rock1"],["water"],["water"],["water"],["water"]],
[["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass_water_tr"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water_grass_br","tree_tl"],["grass_water_tc","tree_tc"],["grass_water_tc","tree_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water"]],
[["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","tree_tl"],["grass","tree_tc"],["grass_water_tr","tree_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tl","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"]],
[["grass","tree_tl"],["grass","tree_tc"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"]],
[["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","bush"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_br"],["grass"],["grass"],["grass","bush_bl"],["grass","bush_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]]
    ],

    (2, 0): [
[["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass_water_br","barrier"],["grass_water_bc","barrier"],["water_grass_tl","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"]],
[["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water","tree_tr"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"]],
[["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water","water_rock1"],["water"],["water","water_rock3"],["water","water_rock2"],["water"],["water_grass_br"],["grass_water_tc","tree_ml"],["grass_water_tc","tree_mc"],["water_grass_bl","tree_mr"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["water"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass","tree_bl"],["grass","tree_bc"],["grass_water_mr","tree_br"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"]],
[["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water","water_rock1"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water","water_rock1"],["water"],["water"],["water"],["water_grass_br"],["grass"],["grass"]],
[["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water"],["water"],["water","water_rock1"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"]],
[["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water_grass_br"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water","tree_tr"],["water_grass_br"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"]],
[["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tr"],["grass"],["grass"],["grass"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc","tree_ml"],["grass_water_tc","tree_mc"],["grass_water_tc","tree_mr"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"]],
[["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","bush_mr"],["grass","grass_rock3"],["grass","bush_mr"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"]],
[["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass","bush_bl"],["grass","bush_bc"],["grass","bush_br"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]]
    ],

    (3, 0): [
[["water","barrier","trunk_left"],["water","barrier","trunk_center"],["water","barrier","trunk_center"],["water","barrier","trunk_right"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["water","barrier"],["grass_water_ml","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_ml","tree_tc"],["grass","tree_mc","tree_tr"],["grass","tree_mr"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass","tree_ml"],["grass","tree_bl","tree_mc"],["grass","tree_bc","tree_mr"],["grass","tree_br"],["grass","barrier"]],
[["grass_water_tc"],["grass_water_tc","tree_tl"],["grass_water_tc","tree_tc"],["grass_water_tc","tree_tr"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water","water_rock1"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass","barrier"]],
[["grass","tree_tl"],["grass","tree_ml","tree_tc"],["grass","tree_mc","tree_tr"],["grass","tree_mr"],["grass"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass","tree_ml"],["grass","tree_bl","tree_mc"],["grass","tree_bc","tree_mr","tree_tl"],["grass","tree_br","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass_water_br","barrier"]],
[["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl","barrier"]],
[["grass"],["grass","bush"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_ml","tree_tc"],["grass","tree_mc","tree_tr","tree_tl"],["grass","tree_mr","tree_tc"],["grass","tree_tr"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_bl","tree_mc","tree_tl"],["grass","tree_bc","tree_mr","tree_ml","tree_tc"],["grass","tree_br","tree_mc","tree_tr"],["grass","tree_mr"],["grass"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc","tree_ml"],["grass","tree_br","tree_bl","tree_mc"],["grass","tree_bc","tree_mr"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water","water_rock1"],["water"],["water"],["water"],["water","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc","barrier"]]
    ],

    (0, 1): [
[["grass","barrier"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_ml","tree_tr"],["grass","tree_mc"],["grass","tree_mr"],["grass"]],
[["grass","barrier"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_left"],["grass","trunk_center"],["grass","trunk_right"],["grass"],["grass","trunk_top"],["grass"],["grass","tree_tl"],["grass","tree_ml","tree_tc"],["grass","tree_mc","tree_tr"],["grass","tree_bl","tree_mr"],["grass","tree_bc","tree_tl"],["grass","tree_br","tree_tc"],["grass","tree_tr"]],
[["grass","barrier"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_middle"],["grass"],["grass","tree_ml"],["grass","tree_bl","tree_mc"],["grass","tree_bc","tree_mr"],["grass","grass_rock2","tree_br"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_middle"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","tree_bc"],["grass","tree_br"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br","bush_tl"],["grass_water_bc","bush_tc"],["grass_water_bl","bush_tr"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_bottom"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br","bush_tl"],["grass_water_bc","bush_tc"],["water_grass_tl","bush_br"],["water","water_rock2"],["water_grass_tr","bush_bl"],["grass_water_bc","bush_tc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr","grass_rock5"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass_water_mr"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass","tree_tl"],["grass","tree_tc"],["grass","grass_big_rock_tl","tree_tr"],["grass","grass_big_rock_tr","tree_tl"],["grass","tree_tc"],["grass_water_tr","tree_tr"],["water_grass_bl","grass_rock4"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml","bush_mr"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"]],
[["grass","barrier"],["grass","tree_ml"],["grass","tree_mc"],["grass","grass_big_rock_bl","tree_mr"],["grass","grass_big_rock_br","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc","bush_bc"],["grass_water_tl","bush_br"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"]],
[["grass","barrier"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]]
    ],

    (1, 1): [
[["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock5"],["grass","grass_rock3"],["grass","grass_rock3"],["grass","grass_rock4"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock2"],["grass","grass_rock3"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock5"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc","tree_ml"],["grass","bush_tc","tree_mc"],["grass","bush_tc","tree_mr"],["grass","bush_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","bush_bl"],["grass","bush_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass","bush_bl"],["grass","bush_tr"],["grass"],["grass"],["grass"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tr"],["grass","bush_ml"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass","bush_ml"],["grass","bush_tl"],["grass","bush_bc"],["grass","bush_bc"],["grass","bush_br"],["grass"],["grass","bush_bl"],["grass","bush_br"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_bl"],["grass","bush_tr"],["grass"],["grass","bush_bl"],["grass","bush_br"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","bush_ml"],["grass"],["grass"],["grass"],["grass"],["grass","bush_tl","tree_ml"],["grass","bush_tc","tree_mc"],["grass","bush_tc","tree_mr"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","bush_bl"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_br","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"]]
    ],

    (2, 1): [
[["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass_water_br"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass","grass_big_rock_tl"],["grass","grass_big_rock_tr"],["grass"]],
[["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water_grass_tr"],["grass_water_bl"],["grass"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass"]],
[["grass"],["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bl"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water"],["water","trunk_left"],["water","trunk_center"],["water","trunk_center"],["water","trunk_right"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bl"],["grass"],["grass"]],
[["grass"],["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"]],
[["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bl"],["grass"]],
[["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"]],
[["grass"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bl"]],
[["grass"],["grass_water_mr"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tc"],["grass","bush_tc"],["grass_water_tr","bush_tr"],["grass_water_tc"],["water_grass_bl"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"]],
[["grass"],["grass_water_mr"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock5"],["grass"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"]],
[["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass"],["grass"],["grass","grass_rock5"],["grass"],["grass"],["grass"],["grass"],["grass","bush"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"]]
    ],

    (3, 1): [
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock1"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass","barrier"]],
[["grass"],["grass","grass_rock1"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock5"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass","grass_rock1"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass","grass_rock1"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","barrier"]],
[["grass"],["grass"],["grass","grass_rock1"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_tl"],["grass","bush_tc"],["grass","bush_tc"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass","bush_ml"],["grass_water_mr"],["water"],["water"],["water"],["water","water_rock3"],["grass_water_ml"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","barrier"]],
[["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass_water_tl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]]
    ],
    
    (0, 2): [
[["grass","barrier"],["grass"],["grass"],["grass"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl"],["grass"]],
[["grass","barrier"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"]],
[["grass","barrier"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bl"]],
[["grass_water_br","barrier"],["water_grass_tl"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water","tree_tr"],["water"],["water"],["water"],["water"],["grass_water_ml"]],
[["grass_water_mr","barrier"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc","tree_ml"],["grass_water_tc","tree_mc"],["grass_water_tc","tree_mr"],["water_grass_bl"],["water"],["water"],["water"],["grass_water_ml"]],
[["grass_water_mr","barrier"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tl"],["grass","grass_rock5"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass_water_tr"],["water_grass_bl"],["water"],["water"],["grass_water_ml"]],
[["grass_water_mr","barrier"],["water"],["water"],["water"],["water"],["water"],["water_grass_br"],["grass_water_tl","grass_big_rock_tl"],["grass","grass_big_rock_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["water_grass_tl"],["water"],["water"],["grass_water_ml"]],
[["grass_water_mr","barrier"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass"],["grass"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc","trunk_top"],["grass_water_bc"],["grass_water_bl"],["grass"],["grass"],["grass_water_mr"],["water"],["water"],["water_grass_br"],["grass_water_tl"]],
[["grass_water_mr","barrier"],["water"],["water"],["water","water_rock1"],["water"],["water"],["grass_water_ml"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water","trunk_middle"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["grass_water_ml"],["grass"]],
[["grass_water_mr","barrier"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water","water_rock2"],["water"],["water","trunk_middle"],["water"],["water"],["water"],["water","water_rock3"],["water"],["water"],["water"],["grass_water_ml"],["grass"]],
[["grass_water_tr","barrier","grass_big_rock_tl"],["water_grass_bl","grass_big_rock_tr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water","tree_tr"],["water"],["water_grass_br"],["water_grass_bl","trunk_bottom"],["water"],["water","water_rock1"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"]],
[["grass","barrier","grass_big_rock_bl"],["grass_water_mr","grass_big_rock_br"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water","tree_ml"],["water_grass_br","tree_mc"],["grass_water_tc","tree_mr"],["grass_water_tc"],["grass_water_tl"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"]],
[["grass","barrier"],["grass_water_mr"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_br","tree_bl"],["grass_water_tl","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tl"],["grass"]],
[["grass","barrier"],["grass_water_tr","barrier"],["grass_water_tc","barrier"],["grass_water_tc","barrier"],["grass_water_tc","barrier"],["grass_water_tc","barrier"],["grass_water_tc","barrier"],["grass_water_tc","barrier"],["grass_water_tc","barrier"],["grass_water_tl","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"]]
    ],

    (1, 2): [
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_top"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_top"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_middle"],["grass"],["grass","grass_big_rock_tl"],["grass","grass_big_rock_tr"],["grass"],["grass","trunk_middle"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_middle"],["grass"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass"],["grass","trunk_middle"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","trunk_middle","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_middle","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","trunk_left","tree_mr"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_right","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"]]
    ],

    (2, 2): [
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","trunk_left"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_center"],["grass","trunk_right"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"]],
[["grass"],["grass","grass_big_rock_tl"],["grass","grass_big_rock_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"]],
[["grass"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass"],["grass"],["grass"],["grass","grass_rock5"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"]],
[["grass"],["grass","grass_rock5"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass_water_br"],["grass_water_bc"],["water_grass_tl"],["water"],["water"],["water"],["water"]],
[["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water","tree_tr"],["water"]],
[["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water_grass_br","tree_ml"],["water_grass_bl","tree_mc"],["water","tree_mr"],["water"]],
[["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["water_grass_tl"],["water"],["water"],["water"],["water"],["grass_water_ml","tree_bl"],["grass_water_tr","tree_bc"],["water_grass_bl","tree_br"],["water"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_br"],["grass_water_bc"],["grass_water_bc","trunk_top"],["water_grass_tl"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass_water_br"],["water_grass_tl"],["water"]],
[["grass"],["grass","grass_rock5"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass_water_br","tree_tr"],["grass_water_bc"],["water_grass_tl"],["water"],["water","trunk_middle"],["water"],["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["water_grass_tl"],["water"],["water"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass_water_mr","tree_mr"],["water"],["water"],["water"],["water","trunk_middle"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass_water_tr","tree_br"],["grass_water_tc"],["water_grass_bl"],["water"],["water","trunk_middle"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"],["water"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tc","trunk_bottom"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["grass_water_tc"],["water_grass_bl"],["water"],["water_grass_br"],["grass_water_tc"],["grass_water_tc"]],
[["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass_water_tr"],["grass_water_tc"],["grass_water_tl"],["grass"],["grass"]],
[["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"]]
    ],

    (3, 2): [
[["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","barrier"]],
[["grass_water_bc"],["grass_water_bl","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_bl"],["grass","tree_bc","tree_tl"],["grass","tree_br","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass","barrier"]],
[["water"],["grass_water_ml","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bc"],["grass_water_bc"],["grass_water_bl","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","grass_big_rock_tl"],["grass","grass_big_rock_tr"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water_grass_tr"],["grass_water_bc"],["grass_water_bl"],["grass","grass_big_rock_bl"],["grass","grass_big_rock_br"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water"],["water"],["water"],["grass_water_ml"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water","tree_tl"],["water","tree_tc"],["water_grass_br","tree_tr"],["grass_water_tl"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["water"],["water"],["water"],["water"],["water_grass_br","tree_ml"],["grass_water_tc","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["water","tree_tc"],["water","tree_tr"],["water"],["water_grass_br"],["grass_water_tl","tree_bl"],["grass","tree_bc"],["grass","tree_br","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass","barrier"]],
[["grass_water_tc","tree_mc"],["grass_water_tc","tree_mr"],["grass_water_tc"],["grass_water_tl"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass","barrier"]],
[["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_bl","tree_tr"],["grass","tree_bc"],["grass","tree_br"],["grass"],["grass"],["grass"],["grass"],["grass","tree_tl"],["grass","tree_tc"],["grass","tree_tr"],["grass"],["grass"],["grass"],["grass"],["grass","tree_bl"],["grass","tree_bc"],["grass","tree_br"],["grass","barrier"]],
[["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","tree_ml"],["grass","tree_mc"],["grass","tree_mr"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass"],["grass","barrier"]],
[["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier","tree_bl"],["grass","barrier","tree_bc"],["grass","barrier","tree_br"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier","tree_bl"],["grass","barrier","tree_bc"],["grass","barrier","tree_br"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"],["grass","barrier"]]
    ],

}

# Interactables
INTERACTABLES_DATA = {
    # Format : (map_x, map_y): [(x, y, "id", "sprite.png", "name", "description")]
    (0, 0): [
        [500, 500, "ours_brun", "bear.png", "Bear", "It's a bear"],
        [500, 500, "mesange_nonnette", "bird1.png", "Bird1", "It's a bird n°1"],
        [500, 500, "mesange_charbonniere", "bird2.png", "Bird2", "It's a bird n°2"],
        [500, 500, "mesange_bleue", "bird3.png", "Bird3", "It's a bird n°3"],
        [500, 500, "mesange_a_longue_queue", "bird4.png", "Bird4", "It's a bird n°4"],
        [500, 500, "sanglier", "boar.png", "Boar", "It's a boar"],
        [500, 500, "cerf_elaphe", "deer.png", "Deer", "It's a deer"],
        [400, 400, "renard_roux", "fox.png", "Fox", "It's a fox"],
        [500, 500, "lapin_de_garenne", "rabbit.png", "Rabbit", "It's a rabbit"],
        [500, 500, "loup_gris", "wolf.png", "Wolf", "It's a wolf"],
    ],
    (1, 0): [
    ]
}

# Screen dimensions
SCREEN_WIDTH = 24 * TILE_SIZE # Map size X * TILE_SIZE
SCREEN_HEIGHT = 14 * TILE_SIZE # Map size Y * TILE_SIZE